// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMXtwUtD88lvFATPpeub2wfwxLaLxmKDU',
    appId: '1:656647613013:web:970d69d08747fe8f3d02dc',
    messagingSenderId: '656647613013',
    projectId: 'wellmate-55cf1',
    authDomain: 'wellmate-55cf1.firebaseapp.com',
    storageBucket: 'wellmate-55cf1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaoBfe9bVUL3d0-NHab--pqyYSQdz7P6c',
    appId: '1:656647613013:android:c45969c76b0084e13d02dc',
    messagingSenderId: '656647613013',
    projectId: 'wellmate-55cf1',
    storageBucket: 'wellmate-55cf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDErXXy5ihr8ap6_AXGhBvCiCMMbYm_C8E',
    appId: '1:656647613013:ios:7ded62dc534110ec3d02dc',
    messagingSenderId: '656647613013',
    projectId: 'wellmate-55cf1',
    storageBucket: 'wellmate-55cf1.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDErXXy5ihr8ap6_AXGhBvCiCMMbYm_C8E',
    appId: '1:656647613013:ios:7ded62dc534110ec3d02dc',
    messagingSenderId: '656647613013',
    projectId: 'wellmate-55cf1',
    storageBucket: 'wellmate-55cf1.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMXtwUtD88lvFATPpeub2wfwxLaLxmKDU',
    appId: '1:656647613013:web:d9204375583c89b03d02dc',
    messagingSenderId: '656647613013',
    projectId: 'wellmate-55cf1',
    authDomain: 'wellmate-55cf1.firebaseapp.com',
    storageBucket: 'wellmate-55cf1.firebasestorage.app',
  );
}
